Project/urls.py
'''
*@copyright   : ToXSL Technologies Pvt. Ltd. < https://toxsl.com >  
*@author      : Shiv Charan Panjeta < shiv@toxsl.com >
 '''
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from core.views import IndexPageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),

    path('accounts/', include('accounts.urls')),
    path('contact/', include('contact.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
'''
*@copyright   : ToXSL Technologies Pvt. Ltd. < https://toxsl.com >  
*@author      : Shiv Charan Panjeta < shiv@toxsl.com >
 '''
 
from django.urls import path

from .views import (
    LogInView, ResendActivationCodeView, RemindUsernameView, SignUpView, ActivateView, LogOutView,
    ChangeEmailView, ChangeEmailActivateView, ChangeProfileView, ChangePasswordView,
    RestorePasswordView, RestorePasswordDoneView, RestorePasswordConfirmView,
)

app_name = 'accounts'

urlpatterns = [
    path('log-in/', LogInView.as_view(), name='log_in'),
    path('log-out/', LogOutView.as_view(), name='log_out'),

    path('resend/activation-code/', ResendActivationCodeView.as_view(), name='resend_activation_code'),

    path('sign-up/', SignUpView.as_view(), name='sign_up'),
    path('activate/<code>/', ActivateView.as_view(), name='activate'),

    path('restore/password/', RestorePasswordView.as_view(), name='restore_password'),
    path('restore/password/done/', RestorePasswordDoneView.as_view(), name='restore_password_done'),
    path('restore/<uidb64>/<token>/', RestorePasswordConfirmView.as_view(), name='restore_password_confirm'),

    path('remind/username/', RemindUsernameView.as_view(), name='remind_username'),

    path('change/profile/', ChangeProfileView.as_view(), name='change_profile'),
    path('change/password/', ChangePasswordView.as_view(), name='change_password'),
    path('change/email/', ChangeEmailView.as_view(), name='change_email'),
    path('change/email/<code>/', ChangeEmailActivateView.as_view(), name='change_email_activation'),
]

core/urls.py
# -*- coding: utf-8 -*-

'''
*@copyright   : ToXSL Technologies Pvt. Ltd. < https://toxsl.com >  
*@author      : Shiv Charan Panjeta < shiv@toxsl.com >
 '''
from django.conf.urls import url

from .views import *

app_name='core'

urlpatterns = [

    url(r'^$', IndexPageView.as_view(), name='index'),
]

templates/includes/_alerts.html
<!--
*@copyright   : ToXSL Technologies Pvt. Ltd. < https://toxsl.com >  
*@author      : Shiv Charan Panjeta < shiv@toxsl.com >  
-->

{% for message in messages %}
  <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">&times;</button>

    {{ message }}
  </div>
{% endfor %}

templates/includes/_field.html
<!--
*@copyright   : ToXSL Technologies Pvt. Ltd. < https://toxsl.com >  
*@author      : Shiv Charan Panjeta < shiv@toxsl.com >  
-->-->

{% if field.errors %}
  <div class="has-error">
{% endif %}
  <label class="control-label" for="{{ form.name.auto_id }}">
    {{ field.label }}
    {% if field.field.required %}*{% endif %}
  </label>

  {{ field }}

  {% if field.field.help_text %}
    <span class="help-block">{{ field.field.help_text }}</span>
  {% endif %}

  {% if field.errors %}
    {% for error in field.errors %}
      <span class="help-block">{{ error }}</span>
    {% endfor %}
  {% endif %}
{% if field.errors %}
  </div>
{% endif %}

templates/includes/_footer.html
<!--
*@copyright   : ToXSL Technologies Pvt. Ltd. < https://toxsl.com >  
*@author      : Shiv Charan Panjeta < shiv@toxsl.com >  
-->
<div class="clearfix"></div>
<footer class="container-fluid text-center">
  <a href="#main" title="To Top">
    <span class="glyphicon glyphicon-chevron-up"></span>
  </a>
  <p>&nbsp;&nbsp;&nbsp;&copy; Toxsl.com, {% now "Y" %}</a></p>
</footer>

templates/includes/_header.html
<!--
*@copyright   : ToXSL Technologies Pvt. Ltd. < https://toxsl.com >  
*@author      : Shiv Charan Panjeta < shiv@toxsl.com >  
-->
{% load i18n %}
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="{% url 'core:index' %}">Toxsl</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'core:index' %}#about">ABOUT</a></li>
        <li><a href="{% url 'core:index' %}#services">SERVICES</a></li>
        <li><a href="{% url 'core:index' %}#portfolio">PORTFOLIO</a></li>
        <li><a href="{% url 'core:index' %}#contact">CONTACT</a></li>
        {% if request.user.is_authenticated %}
        
         <div class="dropdown pull-right">
			  <button class="dropbtn"><i class="glyphicon glyphicon-home"></i></button>
			<div class="dropdown-content">
			  <ul>
			    <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:change_password' %}">{% trans 'Change password' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:change_profile' %}">{% trans 'Change profile' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:change_email' %}">{% trans 'Change email' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:log_out' %}">{% trans 'Log out' %}</a>
                </li>
		       </ul>
		   </div>
		</div>
        {% else %}
        <li>
                    <a href="{% url 'accounts:log_in' %}">{% trans 'LOG IN' %}</a></li>
        <li>
                   <a href="{% url 'accounts:sign_up' %}">{% trans 'REGISTER' %}</a></li>
                    {% endif %}
      </ul>
    </div>
  </div>
</nav>